### ISSUE TITLE
No "delegating" status

### ISSUE THREAD

**Issue by darosior** [revault/revault-gui#203]
When delegating, we signed with only 2 of the 3 stakeholders and the vaults (actually only one of them) was marked as "active" already.

**Comment by darosior** [comment]
![image](https://user-images.githubusercontent.com/22457751/129486069-2a6d66b7-29c0-4c82-821b-47c690c96e58.png)

**Comment by darosior** [comment]
Hmm it's labelled as "active" by revaultd so maybe it's a revaultd bug

**Comment by edouardparis** [comment]
I did not reproduce the issue.
Currently we do not display anymore vaults that are activating on the delegated panel, we keep them on the secured funds panel until they are fully delegated.
My guess with the confusion is that:
the secured vault on the left is activating and the right one is active and there was a confusion about on which one you were focused.
For less confusion maybe I should reintroduce on the delegated panel the line saying some vaults are waiting full delegation ?
ex:
![2021-05-06T12:31:58,384341236+02:00](https://user-images.githubusercontent.com/6933020/133105385-b1f62c60-1224-4d98-8f54-dc9cdd02a09a.png)

**Comment by darosior** [comment]
>  For less confusion maybe I should reintroduce on the delegated panel the line saying some vaults are waiting full delegation ?

Actually this is what i expected. Why was it removed in the first place?

**Comment by edouardparis** [comment]
because we thought that "activating funds" are still "secured funds" and until it is not active, it was ok to keep it as `secured`.
But I prefer finally to keep the "+ ...., ... " like you expected

**Comment by darosior** [comment]
Arf this is sensible too. It's really bad that we go in circle like that on UI choices.. Let's discuss it today during the meeting!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by danielabrozzoni** [comment]
> It's really bad that we go in circle like that on UI choices.. 

This is why I was saying that we need a UI/UX expert 😭 I really think we would benefit a lot from having someone actually following us while we take choices - sure, asking now and then to designers is fine, but they can't help us that much IMHO (even because understanding how revault works is difficult, and if you don't get how revault works you can't make good design choices)

To recap, as I'm not sure if I understood the problem correctly:
1. When funds are not secured and a stakeholder starts securing them, a "+ ..." appears
2. When funds are secured but not delegated and a stakeholder starts delegating them, no "+ ..." appears

I would say let's be consistent and add the "+ ...", but I see why we decided to drop it in the first place :/

Should we count the funds that are activating in the "secured" tab as well? They are secured, but they shouldn't be there imho. Again, I don't know, and I'll probably change my mind soon anwyays 😭

**Comment by darosior** [comment]
So i think we agreed we need at least to have "delegating" too for now? cc @edouardparis

**Comment by edouardparis** [comment]
Yes, I prefer to have it too
